<Project>
  <!-- Set UnityEnginePath and Il2CppInteropPath for all projects including submodules -->
  <PropertyGroup Condition="'$(UnityEnginePath)' == ''">
    <UnityEnginePath>$(MSBuildThisFileDirectory)src\ShadowsOfDoubtHeadTracking\libs</UnityEnginePath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Il2CppInteropPath)' == ''">
    <Il2CppInteropPath>$(MSBuildThisFileDirectory)src\ShadowsOfDoubtHeadTracking\libs</Il2CppInteropPath>
  </PropertyGroup>
</Project>
